name: Build and deploy

on:
  push: {}
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - build: installer
          - build: portable
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          ./install-build-dependencies.sh
      - name: Build
        run: |
          export SOURCE_DATE_EPOCH=$(git show -s --format=%ct)
          "./build-${{ matrix.build }}.sh"
      - name: Get file name
        id: vars
        run: |
          echo "file_name=$(cd dist && ls *.*)" >> $GITHUB_OUTPUT
      - uses: actions/upload-artifact@v4
        if: github.event_name == 'push'
        with:
          name: ${{ steps.vars.outputs.file_name }}
          path: dist/*

  deploy:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    needs:
      - build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: mkdir dist
      - uses: actions/download-artifact@v4
        with:
          path: ./dist
      - run: ./deploy.sh ./dist/**/*
        env:
          RELEASES_API_KEY: ${{ secrets.GITHUB_TOKEN }}
