name: Nightly builds

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - build: installer
          - build: portable
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          ./install-build-dependencies.sh
      - name: Build
        run: |
          export SOURCE_DATE_EPOCH=$(git show -s --format=%ct)
          "./build-${{ matrix.build }}.sh" "" "" master
      - name: Get file name
        id: vars
        run: |
          echo "file_name=$(cd dist && ls *.*)" >> $GITHUB_OUTPUT
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.vars.outputs.file_name }}
          path: dist/*
